export enum AuditAction {
	ORDER_CREATED = 'ORDER_CREATED',
	ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
	ORDER_SCHEDULE_CHANGED = 'ORDER_SCHEDULE_CHANGED',
	ORDER_TRANSPORT_CHANGED = 'ORDER_TRANSPORT_CHANGED',
}
